[package]
name = "jzero-parser"
version = "0.1.0"
edition = "2024"

[build-dependencies]
lalrpop.workspace = true

[dependencies]
lalrpop-util.workspace = true
jzero-lexer = { path = "../jzero-lexer" }
logos.workspace = true